# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'button' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for button
  #pod 'BlocksKit', '~> 2.2.5'


  target 'buttonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'buttonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
